#!/bin/bash

echo "🔧 Gmail Service Setup"
echo "===================="
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to: https://myaccount.google.com/"
echo "2. Security → 2-Step Verification"
echo "3. App Passwords → Generate App Password"
echo "4. Select 'Mail' app, name it 'Internship Portal'"
echo "5. Copy the 16-character password"
echo ""
echo "Then update your .env file with:"
echo ""
echo "GMAIL_USER=your-gmail@gmail.com"
echo "GMAIL_APP_PASS=the-16-char-app-password"
echo ""
echo "After setting credentials, run: node test-gmail.js"
echo ""
